---
name: Build Bluefin
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:


env:
  IMAGE_DESC: "Bluefin (Starlit Edition)"
  IMAGE_KEYWORDS: "bootc,ublue,universal-blue,bluefin"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/20535390?v=4" # Put your own image here for a fancy profile on https://artifacthub.io/!
  IMAGE_NAME: "${{ github.event.repository.name }}"  # output image name, usually same as repo name
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"
  SOURCE_IMAGE: "ghcr.io/ublue-os/bluefin-dx:stable-daily"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: blacksmith-4vcpu-ubuntu-2404

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # These stage versions are pinned by https://github.com/renovatebot/renovate
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Dagger
        id: setup_dagger
        uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Build Image
        run: |
          ${{ env.IMAGE_NAME }}-container ${{ env.SOURCE_IMAGE }}
        shell: dagger {0}
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          ${{ env.IMAGE_NAME }}-publish \
            ${{ env.SOURCE_IMAGE }} \
            ${{ github.repository_owner }} \
            ${{ env.IMAGE_NAME }} \
            ${{ env.IMAGE_LOGO_URL }} \
            ${{ steps.metadata.outputs.tags }}
        shell: dagger {0}
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          REGISTRY_PASSWORD: ${{ github.token }}